### PR TITLE
Demo title Add files via upload

### PR DESCRIPTION
**Pull request by roperopedopedope**

### CODE REVIEW

**Comment by effigies** [comment]
@SteveSandersonMS Cryptocurrency miner. Please cancel actions, block and report the user. Note that they close and re-open to queue up multiple jobs that will need to be canceled separately.

**Comment by SteveSandersonMS** [comment]
@effigies Thanks. I’m surprised this isn’t something GitHub detects and blocks automatically. Maybe that’s hard.

**Comment by effigies** [comment]
I think it is hard to detect, but blocking CI from new contributors to a repo until the owner approves it seems like an easy way to cut off the bulk of these. I don't really know why they're not doing it.

Also, you still have some running: https://github.com/SteveSandersonMS/BlazorOnGitHubPages/runs/2359070820, https://github.com/SteveSandersonMS/BlazorOnGitHubPages/runs/2359055706

**Comment by SteveSandersonMS** [comment]
Ok thanks. I think this is more of a job for GitHub to police than me, so I’m not planning to take further action on this with any kind of priority.

**Pull request closed without merging**
